insert into states (id, name, country_id) values (1, 'A Coruña', 'es');
insert into states (id, name, country_id) values (2, 'Álava', 'es');
insert into states (id, name, country_id) values (3, 'Albacete', 'es');
insert into states (id, name, country_id) values (4, 'Alicante', 'es');
insert into states (id, name, country_id) values (5, 'Almería', 'es');
insert into states (id, name, country_id) values (6, 'Asturias', 'es');
insert into states (id, name, country_id) values (7, 'Ávila', 'es');
insert into states (id, name, country_id) values (8, 'Badajoz', 'es');
insert into states (id, name, country_id) values (9, 'Baleares', 'es');
insert into states (id, name, country_id) values (10, 'Barcelona', 'es');
insert into states (id, name, country_id) values (11, 'Burgos', 'es');
insert into states (id, name, country_id) values (12, 'Cáceres', 'es');
insert into states (id, name, country_id) values (13, 'Cádiz', 'es');
insert into states (id, name, country_id) values (14, 'Cantabria', 'es');
insert into states (id, name, country_id) values (15, 'Castellón', 'es');
insert into states (id, name, country_id) values (16, 'Ceuta', 'es');
insert into states (id, name, country_id) values (17, 'Ciudad Real', 'es');
insert into states (id, name, country_id) values (18, 'Córdoba', 'es');
insert into states (id, name, country_id) values (19, 'Cuenca', 'es');
insert into states (id, name, country_id) values (20, 'Girona', 'es');
insert into states (id, name, country_id) values (21, 'Granada', 'es');
insert into states (id, name, country_id) values (22, 'Guadalajara', 'es');
insert into states (id, name, country_id) values (23, 'Guipúzcoa', 'es');
insert into states (id, name, country_id) values (24, 'Huelva', 'es');
insert into states (id, name, country_id) values (25, 'Huesca', 'es');
insert into states (id, name, country_id) values (26, 'Jaén', 'es');
insert into states (id, name, country_id) values (27, 'La Rioja', 'es');
insert into states (id, name, country_id) values (28, 'Las Palmas', 'es');
insert into states (id, name, country_id) values (29, 'León', 'es');
insert into states (id, name, country_id) values (30, 'Lleida', 'es');
insert into states (id, name, country_id) values (31, 'Lugo', 'es');
insert into states (id, name, country_id) values (32, 'Madrid', 'es');
insert into states (id, name, country_id) values (33, 'Málaga', 'es');
insert into states (id, name, country_id) values (34, 'Melilla', 'es');
insert into states (id, name, country_id) values (35, 'Murcia', 'es');
insert into states (id, name, country_id) values (36, 'Navarra', 'es');
insert into states (id, name, country_id) values (37, 'Ourense', 'es');
insert into states (id, name, country_id) values (38, 'Palencia', 'es');
insert into states (id, name, country_id) values (39, 'Pontevedra', 'es');
insert into states (id, name, country_id) values (40, 'Salamanca', 'es');
insert into states (id, name, country_id) values (41, 'Santa Cruz de Tenerife', 'es');
insert into states (id, name, country_id) values (42, 'Segovia', 'es');
insert into states (id, name, country_id) values (43, 'Sevilla', 'es');
insert into states (id, name, country_id) values (44, 'Soria', 'es');
insert into states (id, name, country_id) values (45, 'Tarragona', 'es');
insert into states (id, name, country_id) values (46, 'Teruel', 'es');
insert into states (id, name, country_id) values (47, 'Toledo', 'es');
insert into states (id, name, country_id) values (48, 'Valencia', 'es');
insert into states (id, name, country_id) values (49, 'Valladolid', 'es');
insert into states (id, name, country_id) values (50, 'Vizcaya', 'es');
insert into states (id, name, country_id) values (51, 'Zamora', 'es');
insert into states (id, name, country_id) values (52, 'Zaragoza', 'es');
