hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
twitter_login:
    path: /login/check-twitter

google_login:
    path: /login/check-google

facebook_login:
    path: /login/check-facebook
    
instagram_login:
    path: /login/check-instagram
    
security:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    path:   /login_check

logout:
    path:   /logout