hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
test_connect_login:
    path: /login/check-test_connect
    
twitter_login:
    path: /login/check-twitter

google_login:
    path: /login/check-google

facebook_login:
    path: /login/check-facebook
    
instagram_login:
    path: /login/check-instagram
    
security:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    path:   /login_check

logout:
    path:   /logout
    
admin_login_check:
    path:   /admin/login_check

admin_logout:
    path:   /admin/logout
    
company_login_check:
    path:   /company/login_check

company_logout:
    path:   /company/logout