security:
    encoders:
        CoreBundle\Entity\Actor:
            algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_COMPANY, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_COMPANY, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: CoreBundle:BaseActor }
#        my_custom_hwi_provider: { id: oauth.user_provider }

    firewalls:
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    twitter:           "/login/check-twitter"
                    google:           "/login/check-google"
                    facebook:           "/login/check-facebook"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: oauth.user_provider
            pattern:    ^/
            form_login:
                login_path:  /login
                check_path:  /login_check
                use_referer: true
                success_handler: authentication_handler
                failure_handler: authentication_handler
            logout:
                path:   /logout
                target: /
#                success_handler: authentication_handler
            anonymous: true
            http_basic:
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/admin/actor, roles: [ROLE_ADMIN, ROLE_OPTIC] }
        - { path: ^/admin/subscription, roles: [ROLE_ADMIN, ROLE_OPTIC] }
        - { path: ^/admin/newsletter, roles: [ROLE_ADMIN, ROLE_OPTIC] }
        - { path: ^/admin/shipping, roles: [ROLE_ADMIN, ROLE_OPTIC] }
        - { path: ^/admin/sliders, roles: [ROLE_ADMIN,ROLE_CALLCENTER,  ROLE_OPTIC] }
        - { path: ^/admin/dashboard, roles: [ROLE_ADMIN, ROLE_OPTIC] }
        - { path: ^/admin/analitycs, roles: [ROLE_ADMIN, ROLE_OPTIC] }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_OPTIC] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
