services:
    core.mailer:
        class: "CoreBundle\\Service\\Mailer"
        arguments:
            - "@mailer"
            - "@twig"
            - { parameters: %core% }
            - "@router"
            - "@templating"
            - "@kernel"
            - "@notification_manager"
            - "@doctrine.orm.entity_manager"

    authentication_handler:
        class: "CoreBundle\\Handler\\AuthenticationHandler"
        arguments: ["@service_container"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    
    core_locale_listener:
        class: CoreBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
            
    core_twig_extension:
        class: "CoreBundle\\Twig\\CoreExtension"
        calls:
            - [setContainer, ["@service_container"] ]
        tags:
            - { name: twig.extension }
            
    notification_manager:
        class: "CoreBundle\\Service\\NotificationManager"
        calls:
            - [setContainer, ["@service_container"] ] 
            
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
            
    oauth.user_provider:
        class: "CoreBundle\\Service\\OAuthUserProvider"
        tags:
          - { name: user.provider }
        arguments: ["@doctrine", "CoreBundle:BaseActor", {twitter: twitter_id, facebook: facebook_id, google: google_id, instagram: instagram_id}, null, "@security.encoder_factory", "@session"]

    core_manager:
        class: "CoreBundle\\Service\\CoreManager"
        calls:
            - [setContainer, ["@service_container"] ]
        arguments:
          - { parameters: %core% }
          
    core_listener:
        class: "CoreBundle\\EventListener\\CoreEventListener"
        calls: 
            - [setContainer, ["@service_container"] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }
