

services:
    core.mailer:
        class: "CoreBundle\\Service\\Mailer"
        arguments:
            - "@mailer"
            - "@twig"
            - { parameters: %core% }
            - "@router"
            - "@templating"
            - "@kernel"
            - "@doctrine.orm.entity_manager"

    authentication_handler:
        class: "%core.authentication_handler_class%"
        arguments: ["@service_container"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    
    core_locale_listener:
        class: CoreBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
            
    core_twig_extension:
        class: "CoreBundle\\Twig\\CoreExtension"
        calls:
            - [setContainer, ["@service_container"] ]
        tags:
            - { name: twig.extension }
            
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
      
    twig.global:
        class: "CoreBundle\\Service\\TwigGlobal"
        calls:
            - [setContainer, ["@service_container"] ] 
            
    core_manager:
        class: "CoreBundle\\Service\\CoreManager"
        calls:
            - [setContainer, ["@service_container"] ]
        arguments:
          - { parameters: %core% }
          
    core_listener:
        class: "CoreBundle\\EventListener\\CoreEventListener"
        calls: 
            - [setContainer, ["@service_container"] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        
    gedmo.listener.timestampable:
        class: "Gedmo\\Timestampable\\TimestampableListener"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sluggable:
        class: "Gedmo\\Sluggable\\SluggableListener"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            
