insert into country (id, iso3, currency, name) values ('??','???','???','unknown');
insert into country (id, iso3, currency, name) values ('ad','and','eur','andorra');
insert into country (id, iso3, currency, name) values ('ae','are','aed','united arab emirates');
insert into country (id, iso3, currency, name) values ('af','afg','afa','afghanistan');
insert into country (id, iso3, currency, name) values ('ag','atg','xcd','antigua and barbuda');
insert into country (id, iso3, currency, name) values ('ai','aia','xcd','anguilla');
insert into country (id, iso3, currency, name) values ('al','alb','all','albania');
insert into country (id, iso3, currency, name) values ('am','arm','amd','armenia');
insert into country (id, iso3, currency, name) values ('an','ant','ang','netherlands antilles');
insert into country (id, iso3, currency, name) values ('ao','ago','aoa','angola');
insert into country (id, iso3, currency, name) values ('aq','ata','???','antarctica');
insert into country (id, iso3, currency, name) values ('ar','arg','ars','argentina');
insert into country (id, iso3, currency, name) values ('as','asm','usd','american samoa');
insert into country (id, iso3, currency, name) values ('at','aut','eur','austria');
insert into country (id, iso3, currency, name) values ('au','aus','aud','australia');
insert into country (id, iso3, currency, name) values ('aw','abw','awg','aruba');
insert into country (id, iso3, currency, name) values ('az','aze','azm','azerbaijan');
insert into country (id, iso3, currency, name) values ('ba','bih','bam','bosnia and herzegovina');
insert into country (id, iso3, currency, name) values ('bb','brb','bbd','barbados');
insert into country (id, iso3, currency, name) values ('bd','bgd','bdt','bangladesh');
insert into country (id, iso3, currency, name) values ('be','bel','eur','belgium');
insert into country (id, iso3, currency, name) values ('bf','bfa','xof','burkina faso');
insert into country (id, iso3, currency, name) values ('bg','bgr','bgl','bulgaria');
insert into country (id, iso3, currency, name) values ('bh','bhr','bhd','bahrain');
insert into country (id, iso3, currency, name) values ('bi','bdi','bif','burundi');
insert into country (id, iso3, currency, name) values ('bj','ben','xof','benin');
insert into country (id, iso3, currency, name) values ('bm','bmu','bmd','bermuda');
insert into country (id, iso3, currency, name) values ('bn','brn','bnd','brunei darussalam');
insert into country (id, iso3, currency, name) values ('bo','bol','bob','bolivia');
insert into country (id, iso3, currency, name) values ('br','bra','brl','brazil');
insert into country (id, iso3, currency, name) values ('bs','bhs','bsd','the bahamas');
insert into country (id, iso3, currency, name) values ('bt','btn','btn','bhutan');
insert into country (id, iso3, currency, name) values ('bv','bvt','nok','bouvet island');
insert into country (id, iso3, currency, name) values ('bw','bwa','bwp','botswana');
insert into country (id, iso3, currency, name) values ('by','blr','byr','belarus');
insert into country (id, iso3, currency, name) values ('bz','blz','bzd','belize');
insert into country (id, iso3, currency, name) values ('ca','can','cad','canada');
insert into country (id, iso3, currency, name) values ('cc','cck','aud','cocos (keeling) islands');
insert into country (id, iso3, currency, name) values ('cd','cod','cdf','congo, democratic republic of th');
insert into country (id, iso3, currency, name) values ('cf','caf','xaf','central african republic');
insert into country (id, iso3, currency, name) values ('cg','cog','xaf','congo, republic of the');
insert into country (id, iso3, currency, name) values ('ch','che','chf','switzerland');
insert into country (id, iso3, currency, name) values ('ci','civ','xof','cote d''ivoire');
insert into country (id, iso3, currency, name) values ('ck','cok','nzd','cook islands');
insert into country (id, iso3, currency, name) values ('cl','chl','clp','chile');
insert into country (id, iso3, currency, name) values ('cm','cmr','xaf','cameroon');
insert into country (id, iso3, currency, name) values ('cn','chn','cny','china');
insert into country (id, iso3, currency, name) values ('co','col','cop','colombia');
insert into country (id, iso3, currency, name) values ('cr','cri','crc','costa rica');
insert into country (id, iso3, currency, name) values ('cu','cub','cup','cuba');
insert into country (id, iso3, currency, name) values ('cv','cpv','cve','cape verde');
insert into country (id, iso3, currency, name) values ('cx','cxr','aud','christmas island');
insert into country (id, iso3, currency, name) values ('cy','cyp','cyp','cyprus');
insert into country (id, iso3, currency, name) values ('cz','cze','czk','czech republic');
insert into country (id, iso3, currency, name) values ('de','deu','eur','germany');
insert into country (id, iso3, currency, name) values ('dj','dji','djf','djibouti');
insert into country (id, iso3, currency, name) values ('dk','dnk','dkk','denmark');
insert into country (id, iso3, currency, name) values ('dm','dma','xcd','dominica');
insert into country (id, iso3, currency, name) values ('do','dom','dop','dominican republic');
insert into country (id, iso3, currency, name) values ('dz','dza','dzd','algeria');
insert into country (id, iso3, currency, name) values ('ec','ecu','usd','ecuador');
insert into country (id, iso3, currency, name) values ('ee','est','eek','estonia');
insert into country (id, iso3, currency, name) values ('eg','egy','egp','egypt');
insert into country (id, iso3, currency, name) values ('eh','esh','mad','western sahara');
insert into country (id, iso3, currency, name) values ('er','eri','ern','eritrea');
insert into country (id, iso3, currency, name) values ('es','esp','eur','spain');
insert into country (id, iso3, currency, name) values ('et','eth','etb','ethiopia');
insert into country (id, iso3, currency, name) values ('fi','fin','eur','finland');
insert into country (id, iso3, currency, name) values ('fj','fji','fjd','fiji');
insert into country (id, iso3, currency, name) values ('fk','flk','fkp','falkland islands (islas malvinas');
insert into country (id, iso3, currency, name) values ('fm','fsm','usd','micronesia, federated states of');
insert into country (id, iso3, currency, name) values ('fo','fro','dkk','faroe islands');
insert into country (id, iso3, currency, name) values ('fr','fra','eur','france');
insert into country (id, iso3, currency, name) values ('ga','gab','xaf','gabon');
insert into country (id, iso3, currency, name) values ('gb','gbr','gbp','united kingdom');
insert into country (id, iso3, currency, name) values ('gd','grd','xcd','grenada');
insert into country (id, iso3, currency, name) values ('ge','geo','gel','georgia');
insert into country (id, iso3, currency, name) values ('gf','guf','eur','french guiana');
insert into country (id, iso3, currency, name) values ('gh','gha','ghc','ghana');
insert into country (id, iso3, currency, name) values ('gi','gib','gip','gibraltar');
insert into country (id, iso3, currency, name) values ('gl','grl','dkk','greenland');
insert into country (id, iso3, currency, name) values ('gm','gmb','gmd','the gambia');
insert into country (id, iso3, currency, name) values ('gn','gin','gnf','guinea');
insert into country (id, iso3, currency, name) values ('gp','glp','eur','guadeloupe');
insert into country (id, iso3, currency, name) values ('gq','gnq','xaf','equatorial guinea');
insert into country (id, iso3, currency, name) values ('gr','grc','eur','greece');
insert into country (id, iso3, currency, name) values ('gs','sgs','gbp','south georgia and the south sand');
insert into country (id, iso3, currency, name) values ('gt','gtm','gtq','guatemala');
insert into country (id, iso3, currency, name) values ('gu','gum','usd','guam');
insert into country (id, iso3, currency, name) values ('gw','gnb','xof','guinea-bissau');
insert into country (id, iso3, currency, name) values ('gy','guy','gyd','guyana');
insert into country (id, iso3, currency, name) values ('hk','hkg','hkd','hong kong (sar)');
insert into country (id, iso3, currency, name) values ('hm','hmd','aud','heard island and mcdonald island');
insert into country (id, iso3, currency, name) values ('hn','hnd','hnl','honduras');
insert into country (id, iso3, currency, name) values ('hr','hrv','hrk','croatia');
insert into country (id, iso3, currency, name) values ('ht','hti','htg','haiti');
insert into country (id, iso3, currency, name) values ('hu','hun','huf','hungary');
insert into country (id, iso3, currency, name) values ('id','idn','idr','indonesia');
insert into country (id, iso3, currency, name) values ('ie','irl','eur','ireland');
insert into country (id, iso3, currency, name) values ('il','isr','ils','israel');
insert into country (id, iso3, currency, name) values ('in','ind','inr','india');
insert into country (id, iso3, currency, name) values ('io','iot','usd','british indian ocean territory');
insert into country (id, iso3, currency, name) values ('iq','irq','iqd','iraq');
insert into country (id, iso3, currency, name) values ('ir','irn','irr','iran');
insert into country (id, iso3, currency, name) values ('is','isl','isk','iceland');
insert into country (id, iso3, currency, name) values ('it','ita','eur','italy');
insert into country (id, iso3, currency, name) values ('jm','jam','jmd','jamaica');
insert into country (id, iso3, currency, name) values ('jo','jor','jod','jordan');
insert into country (id, iso3, currency, name) values ('jp','jpn','jpy','japan');
insert into country (id, iso3, currency, name) values ('ke','ken','kes','kenya');
insert into country (id, iso3, currency, name) values ('kg','kgz','kgs','kyrgyzstan');
insert into country (id, iso3, currency, name) values ('kh','khm','khr','cambodia');
insert into country (id, iso3, currency, name) values ('ki','kir','aud','kiribati');
insert into country (id, iso3, currency, name) values ('km','com','kmf','comoros');
insert into country (id, iso3, currency, name) values ('kn','kna','xcd','saint kitts and nevis');
insert into country (id, iso3, currency, name) values ('kp','prk','kpw','korea, north');
insert into country (id, iso3, currency, name) values ('kr','kor','krw','korea, south');
insert into country (id, iso3, currency, name) values ('kw','kwt','kwd','kuwait');
insert into country (id, iso3, currency, name) values ('ky','cym','kyd','cayman islands');
insert into country (id, iso3, currency, name) values ('kz','kaz','kzt','kazakhstan');
insert into country (id, iso3, currency, name) values ('la','lao','lak','laos');
insert into country (id, iso3, currency, name) values ('lb','lbn','lbp','lebanon');
insert into country (id, iso3, currency, name) values ('lc','lca','xcd','saint lucia');
insert into country (id, iso3, currency, name) values ('li','lie','chf','liechtenstein');
insert into country (id, iso3, currency, name) values ('lk','lka','lkr','sri lanka');
insert into country (id, iso3, currency, name) values ('lr','lbr','lrd','liberia');
insert into country (id, iso3, currency, name) values ('ls','lso','lsl','lesotho');
insert into country (id, iso3, currency, name) values ('lt','ltu','ltl','lithuania');
insert into country (id, iso3, currency, name) values ('lu','lux','eur','luxembourg');
insert into country (id, iso3, currency, name) values ('lv','lva','lvl','latvia');
insert into country (id, iso3, currency, name) values ('ly','lby','lyd','libya');
insert into country (id, iso3, currency, name) values ('ma','mar','mad','morocco');
insert into country (id, iso3, currency, name) values ('mc','mco','eur','monaco');
insert into country (id, iso3, currency, name) values ('md','mda','mdl','moldova');
insert into country (id, iso3, currency, name) values ('mg','mdg','mgf','madagascar');
insert into country (id, iso3, currency, name) values ('mh','mhl','usd','marshall islands');
insert into country (id, iso3, currency, name) values ('mk','mkd','mkd','macedonia, the former yugoslav r');
insert into country (id, iso3, currency, name) values ('ml','mli','xof','mali');
insert into country (id, iso3, currency, name) values ('mm','mmr','mmk','burma');
insert into country (id, iso3, currency, name) values ('mn','mng','mnt','mongolia');
insert into country (id, iso3, currency, name) values ('mo','mac','mop','macao');
insert into country (id, iso3, currency, name) values ('mp','mnp','usd','northern mariana islands');
insert into country (id, iso3, currency, name) values ('mq','mtq','eur','martinique');
insert into country (id, iso3, currency, name) values ('mr','mrt','mro','mauritania');
insert into country (id, iso3, currency, name) values ('ms','msr','xcd','montserrat');
insert into country (id, iso3, currency, name) values ('mt','mlt','mtl','malta');
insert into country (id, iso3, currency, name) values ('mu','mus','mur','mauritius');
insert into country (id, iso3, currency, name) values ('mv','mdv','mvr','maldives');
insert into country (id, iso3, currency, name) values ('mx','mex','mxn','mexico');
insert into country (id, iso3, currency, name) values ('my','mys','myr','malaysia');
insert into country (id, iso3, currency, name) values ('mz','moz','mzm','mozambique');
insert into country (id, iso3, currency, name) values ('na','nam','nad','namibia');
insert into country (id, iso3, currency, name) values ('nc','ncl','xpf','new caledonia');
insert into country (id, iso3, currency, name) values ('ne','ner','xof','niger');
insert into country (id, iso3, currency, name) values ('nf','nfk','aud','norfolk island');
insert into country (id, iso3, currency, name) values ('ng','nga','ngn','nigeria');
insert into country (id, iso3, currency, name) values ('ni','nic','nio','nicaragua');
insert into country (id, iso3, currency, name) values ('nl','nld','eur','netherlands');
insert into country (id, iso3, currency, name) values ('no','nor','nok','norway');
insert into country (id, iso3, currency, name) values ('np','npl','npr','nepal');
insert into country (id, iso3, currency, name) values ('nr','nru','aud','nauru');
insert into country (id, iso3, currency, name) values ('nu','niu','nzd','niue');
insert into country (id, iso3, currency, name) values ('nz','nzl','nzd','new zealand');
insert into country (id, iso3, currency, name) values ('om','omn','omr','oman');
insert into country (id, iso3, currency, name) values ('pa','pan','pab','panama');
insert into country (id, iso3, currency, name) values ('pe','per','pen','peru');
insert into country (id, iso3, currency, name) values ('pf','pyf','xpf','french polynesia');
insert into country (id, iso3, currency, name) values ('pg','png','pgk','papua new guinea');
insert into country (id, iso3, currency, name) values ('ph','phl','php','philippines');
insert into country (id, iso3, currency, name) values ('pk','pak','pkr','pakistan');
insert into country (id, iso3, currency, name) values ('pl','pol','pln','poland');
insert into country (id, iso3, currency, name) values ('pm','spm','eur','saint pierre and miquelon');
insert into country (id, iso3, currency, name) values ('pn','pcn','nzd','pitcairn islands');
insert into country (id, iso3, currency, name) values ('pr','pri','usd','puerto rico');
insert into country (id, iso3, currency, name) values ('ps','pse','???','palestinian territory, occupied');
insert into country (id, iso3, currency, name) values ('pt','prt','eur','portugal');
insert into country (id, iso3, currency, name) values ('pw','plw','usd','palau');
insert into country (id, iso3, currency, name) values ('py','pry','pyg','paraguay');
insert into country (id, iso3, currency, name) values ('qa','qat','qar','qatar');
insert into country (id, iso3, currency, name) values ('re','reu','eur','ržunion');
insert into country (id, iso3, currency, name) values ('ro','rou','rol','romania');
insert into country (id, iso3, currency, name) values ('ru','rus','rub','russia');
insert into country (id, iso3, currency, name) values ('rw','rwa','rwf','rwanda');
insert into country (id, iso3, currency, name) values ('sa','sau','sar','saudi arabia');
insert into country (id, iso3, currency, name) values ('sb','slb','sbd','solomon islands');
insert into country (id, iso3, currency, name) values ('sc','syc','scr','seychelles');
insert into country (id, iso3, currency, name) values ('sd','sdn','sdd','sudan');
insert into country (id, iso3, currency, name) values ('se','swe','sek','sweden');
insert into country (id, iso3, currency, name) values ('sg','sgp','sgd','singapore');
insert into country (id, iso3, currency, name) values ('sh','shn','shp','saint helena');
insert into country (id, iso3, currency, name) values ('si','svn','sit','slovenia');
insert into country (id, iso3, currency, name) values ('sj','sjm','nok','svalbard');
insert into country (id, iso3, currency, name) values ('sk','svk','skk','slovakia');
insert into country (id, iso3, currency, name) values ('sl','sle','sll','sierra leone');
insert into country (id, iso3, currency, name) values ('sm','smr','eur','san marino');
insert into country (id, iso3, currency, name) values ('sn','sen','xof','senegal');
insert into country (id, iso3, currency, name) values ('so','som','sos','somalia');
insert into country (id, iso3, currency, name) values ('sr','sur','srg','suriname');
insert into country (id, iso3, currency, name) values ('st','stp','std','s‹o tomž and pr’ncipe');
insert into country (id, iso3, currency, name) values ('sv','slv','svc','el salvador');
insert into country (id, iso3, currency, name) values ('sy','syr','syp','syria');
insert into country (id, iso3, currency, name) values ('sz','swz','szl','swaziland');
insert into country (id, iso3, currency, name) values ('tc','tca','usd','turks and caicos islands');
insert into country (id, iso3, currency, name) values ('td','tcd','xaf','chad');
insert into country (id, iso3, currency, name) values ('tf','atf','eur','french southern and antarctic la');
insert into country (id, iso3, currency, name) values ('tg','tgo','xof','togo');
insert into country (id, iso3, currency, name) values ('th','tha','thb','thailand');
insert into country (id, iso3, currency, name) values ('tj','tjk','tjs','tajikistan');
insert into country (id, iso3, currency, name) values ('tk','tkl','nzd','tokelau');
insert into country (id, iso3, currency, name) values ('tl','tls','tpe','east timor');
insert into country (id, iso3, currency, name) values ('tm','tkm','tmm','turkmenistan');
insert into country (id, iso3, currency, name) values ('tn','tun','tnd','tunisia');
insert into country (id, iso3, currency, name) values ('to','ton','top','tonga');
insert into country (id, iso3, currency, name) values ('tr','tur','trl','turkey');
insert into country (id, iso3, currency, name) values ('tt','tto','ttd','trinidad and tobago');
insert into country (id, iso3, currency, name) values ('tv','tuv','aud','tuvalu');
insert into country (id, iso3, currency, name) values ('tw','twn','twd','taiwan');
insert into country (id, iso3, currency, name) values ('tz','tza','tzs','tanzania');
insert into country (id, iso3, currency, name) values ('ua','ukr','uah','ukraine');
insert into country (id, iso3, currency, name) values ('ug','uga','ugx','uganda');
insert into country (id, iso3, currency, name) values ('um','umi','usd','united states minor outlying island');
insert into country (id, iso3, currency, name) values ('us','usa','usd','united states');
insert into country (id, iso3, currency, name) values ('uy','ury','uyu','uruguay');
insert into country (id, iso3, currency, name) values ('uz','uzb','uzs','uzbekistan');
insert into country (id, iso3, currency, name) values ('va','vat','eur','holy see (vatican city)');
insert into country (id, iso3, currency, name) values ('vc','vct','xcd','saint vincent and the grenadines');
insert into country (id, iso3, currency, name) values ('ve','ven','veb','venezuela');
insert into country (id, iso3, currency, name) values ('vg','vgb','usd','british virgin islands');
insert into country (id, iso3, currency, name) values ('vi','vir','usd','virgin islands');
insert into country (id, iso3, currency, name) values ('vn','vnm','vnd','vietnam');
insert into country (id, iso3, currency, name) values ('vu','vut','vuv','vanuatu');
insert into country (id, iso3, currency, name) values ('wf','wlf','xpf','wallis and futuna');
insert into country (id, iso3, currency, name) values ('ws','wsm','wst','samoa');
insert into country (id, iso3, currency, name) values ('ye','yem','yer','yemen');
insert into country (id, iso3, currency, name) values ('yt','myt','eur','mayotte');
insert into country (id, iso3, currency, name) values ('yu','yug','yum','yugoslavia');
insert into country (id, iso3, currency, name) values ('za','zaf','zar','south africa');
insert into country (id, iso3, currency, name) values ('zw','zwe','zwd','zimbabwe');

